apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret-{{ .Release.Name }}
  labels:
    {{- include "mssql-latest.labels" . | nindent 4 }}
type: Opaque
data:
 sa_password : {{ .Values.sa_password | b64enc | quote}}